import { z } from "zod";

/**
 * Structured facts extracted from an incident's impacted repository by a
 * RepoContextProvider (GitAgent, plain local git, or a mock). This is
 * deliberately provider-agnostic: it carries repo *facts*, not reasoning —
 * the reasoning happens downstream in the Featherless-powered RCA agent.
 */
export const RepoCommitSchema = z.object({
  sha: z.string(),
  author: z.string(),
  message: z.string(),
  date: z.string(),
  changedFiles: z.array(z.string()).default([]),
});
export type RepoCommit = z.infer<typeof RepoCommitSchema>;

export const RepoContextProviderName = {
  GITAGENT: "gitagent",
  LOCAL_GIT: "local-git",
  MOCK: "mock",
  NONE: "none",
} as const;
export const RepoContextProviderNameSchema = z.nativeEnum(RepoContextProviderName);
export type RepoContextProviderName = z.infer<typeof RepoContextProviderNameSchema>;

/** One investigator question and the archaeologist's (GitAgent) answer. */
export const RepoInvestigationItemSchema = z.object({
  question: z.string(),
  answer: z.string(),
});
export type RepoInvestigationItem = z.infer<typeof RepoInvestigationItemSchema>;

export const RepoContextSchema = z.object({
  available: z.boolean(),
  provider: RepoContextProviderNameSchema,
  repo: z.string().nullable(),
  ref: z.string().nullable(),
  recentCommits: z.array(RepoCommitSchema).default([]),
  changedFiles: z.array(z.string()).default([]),
  // commits/files whose text overlaps the incident signal — the likely culprits.
  suspectSignals: z.array(z.string()).default([]),
  // Multi-agent investigation: Featherless-generated questions answered by
  // GitAgent's repo archaeology.
  investigation: z.array(RepoInvestigationItemSchema).default([]),
  summary: z.string(),
});
export type RepoContext = z.infer<typeof RepoContextSchema>;

export const RepoContextRequestSchema = z.object({
  service: z.string(),
  incidentSummary: z.string(),
  category: z.string(),
  sinceMinutes: z.number().default(1440),
  // Runtime repo URL/path override. When set (e.g. a URL pasted in the UI),
  // providers analyze it directly instead of resolving service via the static
  // INCIDENT_REPO_MAP.
  repoUrl: z.string().optional(),
  // Multi-agent mode: investigation questions (generated by Featherless) for
  // the GitAgent archaeologist to answer against the repo history. When
  // present, the gitagent provider answers each; otherwise it runs a single
  // default analysis.
  questions: z.array(z.string()).optional(),
});
export type RepoContextRequest = z.infer<typeof RepoContextRequestSchema>;

/** Body for POST /api/repo-analysis — "postmortem this GitHub repo". */
export const RepoAnalysisInputSchema = z.object({
  repoUrl: z
    .string()
    .url()
    .refine((u) => /github\.com|gitlab\.com|\.git$/.test(u) || u.startsWith("http"), "Expected a git repository URL"),
  context: z.string().max(2000).optional(),
});
export type RepoAnalysisInput = z.infer<typeof RepoAnalysisInputSchema>;

/** Derives a short service label ("owner/name") from a git repo URL. */
export function serviceFromRepoUrl(repoUrl: string): string {
  const cleaned = repoUrl.replace(/\.git$/, "").replace(/\/$/, "");
  const parts = cleaned.split("/").filter(Boolean);
  const name = parts.at(-1) ?? "repository";
  const owner = parts.at(-2);
  return owner && owner !== "github.com" && !owner.includes(":") ? `${owner}/${name}` : name;
}
